### ISSUE TITLE
Enhancement:  Make Password/PIN pop-up more legible

### ISSUE THREAD

**Issue by GoogleCodeExporter** [rogerta/secrets-for-android#96] opened 2015-03-14 04:17 UTC
```
When short pressing on an item to get your Password/PIN, the pop-up box and 
information inside are difficult to read because the other text remains on the 
screen.

Enhancement would be for the screen to go blank except for the Password/PIN 
pop-up box, making it easier to read.
```

Original issue reported on code.google.com by `neverupn...@gmail.com` on 17 Feb 2011 at 6:19

**Comment by bcwhite0** [comment] 2021-05-12 21:23
This is a duplicate of
https://github.com/rogerta/secrets-for-android/issues/95

**Closed by bcwhite0** 2021-05-12 21:23 UTC
Labels: Priority-Low, Type-Enhancement, auto-migrated
